["protostar.config"]
protostar_version = "0.2.4"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = ["src/main.cairo"]
boolean_contract = ["src/boolean_contract.cairo"]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]